### ISSUE TITLE
Merge with react-tether2

### ISSUE THREAD

**Issue by gabrielbull** [souporserious/react-tether#22]
Hello,

I've tried using this library but was limited by how the target needs to be a children of the source and also by how the react component is moved in the DOM after rendering.

This led me to write my own wrapper around tether (https://github.com/gabrielbull/react-tether2). If you are interested in merging the two libraries let me know.

Regards,
Gabriel Bull

**Comment by souporserious** [comment]
What is limiting you right now? I actually had something similar to what you have in an earlier version of this library. It sounds like `renderElementTo` could fix your problem? The reason for passing the target as a child is you don't have to rely on refs to pass it in. I was running into an issue where I would have to `forceUpdate` a component to get the ref.

**Comment by gabrielbull** [comment]
No worries, I was just trying to see if it was a good idea to merge the two projects. In my case it is not possible to always have the target be a children of the source. In this case, it is possible to pass an HTML Element, a React Component, or a React reference as a target in my library, providing more options.

As for `renderElementTo`, it is not exactly what I wanted either. I find that it is better practice to keep away from altering the rendering process. In my library, the React Component is rendered directly where the user puts it without using `ReactDOM.render`.

**Comment by souporserious** [comment]
Yeah the main benefit of using a "portal" is that you can have things like dropdown's that get appended at the end of the DOM easily. We were running into overflow issues at my work where a dropdown needed to be appended at the end of the DOM, hence why it is like that. In your case you could just build a component and have that accept the second child as a prop right? Just trying to understand what benefits my solution doesn't provide. Would love to have one solid solution rather than two.
